import localFont from "next/font/local";
import { Gluten, Libre_Barcode_128_Text, Yatra_One} from "next/font/google"
import "./globals.css";

// all the fonts we import are functions, and they take an object of 'settings' as an argument. 

export const gluten = Gluten({
  subsets: ['latin'],
})

// yatra_one has a css varible name of --font-*
// it HAS to start with --font-
// make sure to apple to the body so the app can use it.
const yatra_one = Yatra_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-yatra_one'
})


export const barcode = Libre_Barcode_128_Text({
  weight: '400',
  subsets: ['latin']
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${yatra_one.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
