import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// we don't have a head tag. 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// layout.js is really nice for adding nav bars/footers things like that.

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
       <div id='hello'>
        {children}
       </div>
      </body>
    </html>
  );
}

