import {Gluten, Yellowtail} from "next/font/google"
import "./globals.css";
import NavBar from "@/components/NavBar";


export const gluten = Gluten({
  subsets: ['latin']
})

// when you set variables for fonts, it has start --font-
// allows us to use the font in our css files
const yellowtail = Yellowtail({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-yellowtail'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gluten.className} ${yellowtail.variable} antialiased`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
